### PR TITLE
Package as a Webextension to support Firefox 57+

### PR DESCRIPTION
**Pull request by MikkCZ**
I have tested the extension in Firefox and it works. There are still few questions left:
- You may want to specify the [min version for Firefox](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/version). If you do not want to test the compatibility in older versions, just put there 56.0 or 57.0. If there is any older version worth testing, it would be 52.0, which is ESR (extended support + last version for XP and Vista).
- To be able to upload to AMO, there might be a [version](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/version) bump needed.
- [web-ext](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) is a pretty neat tool. What about using it instead of make, or use make to wrap it?

There is some code that may be polished a bit for the current state of browsers API, but that I will cover later, as it's not in the scope of porting to Firefox 57.

### CODE REVIEW

**Comment by MikkCZ** [comment]
@foxik r?

**Comment by foxik** [comment]
Thanks for the pull request. Currently I am ill, but I will try to get to it as soon as possible (I definitely want to test Firefox 52, I do not have newer versions on any of my compupters).

**Comment by foxik** [comment]
Merging. Thanks for your work.

The plugin seems to work on Firefox 52, but when loading it as a Temporary Add-on, the browser.runtime.onInstalled and browser.runtime.onStartup do not fire -- but when adding a direct call to the context menu creation, the plugins works. At this point I am assuming it is only a problem with the Temporary Add-on, but maybe I am doing the initialization wrong.

**Comment by MikkCZ** [comment]
I will look at the initialization issue during the OpenAlt conference next week, where I will have a great opportunity during the WebExtensions API workshop. ;)

**Pull request merged**
